### ISSUE TITLE
Remove "/fitter_happier" prefix from routes

### ISSUE THREAD

**Issue by ecbrodie** [nulogy/fitter-happier#5]
Currently, Fitter-Happier is not following best practices for Rails Engine Routes. All routes have a prefix of `"/fitter_happier"` applied to them. This means that Rails applications using Fitter-Happier will either need to mount the Engine routes onto `"/"` or onto some other named route path. The former is a code smell because mounting the routes onto the root route is potentially dangerous. The latter case is just verbose.

Instead, we should remove the `"/fitter_happier"` prefix from this project's code and allow the Rails application using Fitter-Happier to have the freedom to choose how to mount the routes.

Thank you for reporting this IRL @jchunky!

**Comment by amckinnell** [comment]
Better design. And not going to do it yet.
